BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        text: 'one'
    TextInput:
        id : input_name
        text: ''

    Button:
        text: 'three'
    Label:
        text: "enter your name"
        color: (1, 1, 0, 1)
    Button:
        text: "Greet"
        on_press: app.handle_greet()
    Label:
        id: output_label
        text: "Hi"
        color: (1,1,0,1)