BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
            text: ''
            font_size: 48
            multiline: False
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Up'
            Button:
                text: 'Down'
    Button:
        text: 'Covert m to km'
    Label:
        text: 'Answer'
        color: (1,1,0,1)